// TODO: replace with real data from GET /api/tutors
export const MOCK_TUTORS = [
  {
    id: '11111111-0000-0000-0000-000000000001',
    firstName: 'Alex',
    lastName: 'Chen',
    email: 'achen@ilstu.edu',
    bio: 'Junior IT major. Loves algorithms and data structures.',
    userType: 'TUTOR',
    emailVerified: true,
    courses: ['IT 179', 'IT 279', 'IT 168'],
    rating: 4.9,
    reviews: 42,
    rate: '$15/hr',
    mode: 'Both',
    available: true,
    avatar: 'AC',
    avatarBg: '#CE1126',
    year: 'Junior',
  },
  {
    id: '11111111-0000-0000-0000-000000000002',
    firstName: 'Jordan',
    lastName: 'Lee',
    email: 'jlee@ilstu.edu',
    bio: 'Senior IT major with focus on web and cloud technologies.',
    userType: 'TUTOR',
    emailVerified: true,
    courses: ['IT 353', 'IT 354', 'IT 358'],
    rating: 4.7,
    reviews: 28,
    rate: '$12/hr',
    mode: 'Online',
    available: true,
    avatar: 'JL',
    avatarBg: '#1D4ED8',
    year: 'Senior',
  },
  {
    id: '11111111-0000-0000-0000-000000000003',
    firstName: 'Sam',
    lastName: 'Rivera',
    email: 'srivera@ilstu.edu',
    bio: 'Graduate student specializing in cybersecurity and networking.',
    userType: 'TUTOR',
    emailVerified: true,
    courses: ['IT 250', 'IT 357', 'IT 359'],
    rating: 4.8,
    reviews: 35,
    rate: '$10/hr',
    mode: 'In-Person',
    available: false,
    avatar: 'SR',
    avatarBg: '#7C3AED',
    year: 'Graduate',
  },
  {
    id: '11111111-0000-0000-0000-000000000004',
    firstName: 'Taylor',
    lastName: 'Kim',
    email: 'tkim@ilstu.edu',
    bio: 'Sophomore with strong foundation in programming fundamentals.',
    userType: 'TUTOR',
    emailVerified: true,
    courses: ['IT 168', 'IT 164', 'IT 178'],
    rating: 4.6,
    reviews: 19,
    rate: '$14/hr',
    mode: 'Both',
    available: true,
    avatar: 'TK',
    avatarBg: '#0369A1',
    year: 'Sophomore',
  },
  {
    id: '11111111-0000-0000-0000-000000000005',
    firstName: 'Morgan',
    lastName: 'Davis',
    email: 'mdavis@ilstu.edu',
    bio: 'Senior IT major. Specializes in databases and software engineering.',
    userType: 'TUTOR',
    emailVerified: true,
    courses: ['IT 378', 'IT 326', 'IT 363'],
    rating: 5.0,
    reviews: 11,
    rate: '$18/hr',
    mode: 'Online',
    available: true,
    avatar: 'MD',
    avatarBg: '#065F46',
    year: 'Senior',
  },
];

// TODO: replace with real data from GET /api/sessions
export const MOCK_SESSIONS = [
  {
    id: 'sess-001',
    tutorIndex: 0,
    course: 'IT 279',
    date: 'Mar 10',
    time: '3:00 PM',
    mode: 'Online',
    status: 'upcoming',
  },
  {
    id: 'sess-002',
    tutorIndex: 4,
    course: 'IT 378',
    date: 'Mar 12',
    time: '1:00 PM',
    mode: 'In-Person',
    status: 'upcoming',
  },
  {
    id: 'sess-003',
    tutorIndex: 1,
    course: 'IT 353',
    date: 'Mar 4',
    time: '2:00 PM',
    mode: 'Online',
    status: 'completed',
  },
];

// TODO: replace with real data from GET /api/messages/conversations
export const MOCK_MESSAGES = [
  {
    id: 'conv-001',
    tutorIndex: 0,
    lastMessage: 'See you Tuesday at 3pm!',
    lastTime: '2m',
    unreadCount: 2,
    messages: [
      { id: 'm1', from: 'them', text: 'Hey! Ready for Tuesday?',                timestamp: '10:00 AM' },
      { id: 'm2', from: 'me',   text: 'Yes! I have questions about recursion.',  timestamp: '10:02 AM' },
      { id: 'm3', from: 'them', text: 'See you Tuesday at 3pm!',                timestamp: '10:03 AM' },
    ],
  },
  {
    id: 'conv-002',
    tutorIndex: 4,
    lastMessage: 'I can help with that assignment.',
    lastTime: '1h',
    unreadCount: 0,
    messages: [
      { id: 'm4', from: 'me',   text: 'Hey, do you have time this week?',        timestamp: '9:00 AM' },
      { id: 'm5', from: 'them', text: 'I can help with that assignment.',        timestamp: '9:30 AM' },
    ],
  },
  {
    id: 'conv-003',
    tutorIndex: 1,
    lastMessage: 'Thanks for the session!',
    lastTime: '3h',
    unreadCount: 0,
    messages: [
      { id: 'm6', from: 'me',   text: 'That session was super helpful!',         timestamp: '8:00 AM' },
      { id: 'm7', from: 'them', text: 'Thanks for the session!',                 timestamp: '8:15 AM' },
    ],
  },
];
