spring.application.name=backend

# Database configuration for Neon Cloud 
spring.datasource.url=jdbc:postgresql://ep-royal-base-ae6zbu1k.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${NEON_DB_USERNAME}
spring.datasource.password=${NEON_DB_PASSWORD}
#${NEON_DB_USERNAME}
#${NEON_DB_PASSWORD}

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

#SQL init
spring.sql.init.mode=always

# Connection pool settings (HikariCP)
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=1
spring.datasource.hikari.connectionTimeout=20000

# CORS Configuration
app.cors.allowed-origins=http://localhost:3000,http://10.0.2.2:3000

# Server port
server.port=8080

# Email configuration 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=peertutorisu@gmail.com
spring.mail.password=fmxk uomh saqh ixyt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App base URL for verification links
app.base-url=http://localhost:8080
