INSERT INTO courses (course_number, course_name) VALUES ('IT 140', 'Interacting In A Digital World') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 150', 'Using Microcomputer Productivity Tools') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 163', 'Introductory C Programming for Engineers') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 164', 'Introduction To Problem Solving Using The Computer') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 166', 'Python Programming For Science and Data Analysis') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 168', 'Structured Problem Solving Using The Computer') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 170', 'Scripting Languages and Automation') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 178', 'Computer Application Programming') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 179', 'Introduction To Data Structures') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 180', 'C++ Programming') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 191', 'Introduction To IT Professional Practice') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 214', 'Social, Legal, And Ethical Issues In Information Technology') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 215', 'Introduction to Applied Artificial Intelligence') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 225', 'Computer Organization') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 244', 'Business Analytics for Artificial Intelligence') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 250', 'Fundamentals of Information Assurance and Security') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 254', 'Hardware And Software Concepts') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 261', 'Systems Development I') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 262', 'Information Technology Project Management') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 272', 'Cobol As A Second Language') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 275', 'Java As A Second Language') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 276', 'Data Communications') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 279', 'Algorithms And Data Structures') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 287', 'Independent Study') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 299', 'Independent Honor Study') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 310', 'Cloud Networking') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 311', 'Internet of Things') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 312', 'Applications of Artificial Intelligence and Machine Learning') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 326', 'Principles Of Software Engineering') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 327', 'Concepts Of Programming Languages') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 328', 'Introduction To The Theory Of Computation') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 329', 'Compiler Design') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 330', 'Introduction To Enterprise Computer Systems') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 340', 'Introduction To Artificial Intelligence') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 344', 'Techniques and Tools in Applied Machine Learning') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 348', 'Introduction to Machine Learning') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 350', 'Operating Systems Concepts and Administration') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 351', 'Practical Cryptography and Trusted Systems') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 352', 'Data and Information Visualization') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 353', 'Web Development Technologies') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 354', 'Advanced Web Application Development') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 355', 'Secure Software Development') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 356', 'Introduction To Computer Graphics') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 357', 'Tools And Techniques In Defensive Security') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 358', 'Mobile and Cloud Computing') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 359', 'Tools And Techniques in Penetration Testing') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 360', 'Security Incident And Event Management And Forensics') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 363', 'Systems Development II') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 367', 'Designing The User Interface') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 368', 'Topics In Information Systems') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 368A17', 'Enterprise Resource Planning') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 369', 'Topics In Cybersecurity') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 369A02', 'Applied Quantum Machine Learning') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 369A03', 'Advanced Artificial Intelligence') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 369A04', 'Principles of Containers and Cloud Services') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 370', 'Server Management') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 372', 'External Data Structures') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 373', 'Wide Area Network Infrastructures') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 376', 'Wireless And Mobile Network Security') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 377', 'Practical Telecommunication Networking') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 378', 'Database Processing') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 379', 'Advanced Computer Networks') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 380', 'Wireless Communication Systems') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 381', 'Network Design And Analysis') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 383', 'Principles Of Operating Systems') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 386', 'Introduction to Networking and Parallel and Distributed Computing') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 388', 'Parallel Processing') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 391', 'Directed Project In Information Technology') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 398', 'Professional Practice: Information Technology') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 398A50', 'Professional Practice: Coop In Information Technology') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 398A60', 'Professional Practice: Coop In Information Technology') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 400', 'Independent Study') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 401', 'Computer Systems and Basic Python Programming') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 402', 'Implementation of Data Structures and Algorithm') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 426', 'Advanced Software Engineering') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 427', 'Design and Analysis of Algorithms') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 428', 'Fundamental Theory of Computer Science') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 429', 'Compiler Design') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 432', 'Systems Analysis And Design') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 440', 'Introduction to Artificial Intelligence') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 441', 'Big Data') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 444', 'Data Analytics and Mining') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 448', 'Introduction to Machine Learning') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 450', 'Policy & Administration In Information Assurance & Security') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 451', 'Practical Cryptography and Trusted Systems') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 452', 'Data and Information Visualization') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 453', 'Web Development Technologies') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 454', 'Advanced Web Application Development') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 456', 'Introduction to Computer Graphics') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 457', 'Tools and Techniques in Defensive Security') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 458', 'Mobile and Cloud Computing') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 463', 'Information Technology Project Management') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 467', 'Human Factors In Information Systems') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 468', 'Software Quality Assurance And Testing') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 468A17', 'Enterprise Resource Planning') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 470', 'Server Management') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 475', 'Practical Telecommunication Networking') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 476', 'Wireless And Mobile Network Security') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 477', 'Converged Network Architectures') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 478', 'Advanced Database Management') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 479', 'Advanced Computer Networks') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 481', 'Network Design And Analysis') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 482', 'Distributed Systems') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 483', 'Advanced Operating Systems') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 487', 'Parallel Processing') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 488', 'Topics in Computer Science') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 494', 'Graduate Directed Project') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 495', 'Information Technology Capstone') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 496', 'Information Technology Strategy & Policy') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 497', 'Introduction To Research Methodology') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 498', 'Professional Practice: Information Technology') ON CONFLICT (course_number) DO NOTHING;
INSERT INTO courses (course_number, course_name) VALUES ('IT 499', 'Independent Research For The Master''s Thesis') ON CONFLICT (course_number) DO NOTHING;